require:
  - rubocop-factory_bot
  - rubocop-rails
  - rubocop-rspec
  - rubocop-rspec_rails

AllCops:
  NewCops: enable

Gemspec/AddRuntimeDependency:
  Enabled: true

Gemspec/DeprecatedAttributeAssignment:
  Enabled: true

Gemspec/DevelopmentDependencies:
  Enabled: true

Gemspec/RequireMFA:
  Enabled: true

Layout/LineContinuationLeadingSpace:
  Enabled: true

Layout/LineContinuationSpacing:
  Enabled: true

Layout/LineEndStringConcatenationIndentation:
  Enabled: true

Layout/SpaceBeforeBrackets:
  Enabled: true

Layout/ArgumentAlignment:
  Enabled: false

Layout/HashAlignment:
  Enabled: false

Lint/AmbiguousAssignment:
  Enabled: true

RSpecRails/InferredSpecType:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false

RSpec/MultipleMemoizedHelpers:
  Enabled: false

RSpec/VerifiedDoubles:
  Enabled: false

RSpec/NamedSubject:
  Enabled: false

RSpec/ExampleLength:
  Max: 10

RSpec/AnyInstance:
  Enabled: false

Metrics/AbcSize:
  Exclude:
    - 'db/migrate/**/*.rb'

Metrics/MethodLength:
  Exclude:
    - 'db/migrate/**/*.rb'
