default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: tech_playground_api_development

test:
  <<: *default
  database: tech_playground_api_test

production:
  <<: *default
  database: tech_playground_api_production
  username: tech_playground_api
  password: <%= ENV["TECH_PLAYGROUND_API_DATABASE_PASSWORD"] %>
